spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #healthCheckPath: ${management.contextPath}/health
        #healthCheckPath: /health
        healthCheckInterval: 15s
        instance-id: consul2
        enabled: true
      enabled: true
  application:
    name: consul2
server:
  port: 8082

management:
     endpoints:
       web:
         exposure:
           include: '*'